CREATE SCHEMA `bytedb` ;

CREATE TABLE `bytedb`.`empresas` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NOMBRE` VARCHAR(45) NOT NULL,
  `NIT` VARCHAR(10) NOT NULL,
  `FECHA_FUNDACION` DATE NOT NULL,
  `DIRECCION` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`ID`)
);
